#!/usr/bin/env python3
"""
update-gallery.py — Regenerate photos/manifest.json from files in photos/.

Usage:
    python3 update-gallery.py             # scan and update manifest.json
    python3 update-gallery.py --dry       # preview changes without writing
    python3 update-gallery.py --rebuild   # regenerate ALL captions from filenames
                                          # (discards existing manual captions —
                                          # use after improving filename conventions)

Workflow:
    1. Drop new photos (.webp / .jpg / .jpeg / .png) into the photos/ folder.
    2. (Optional) Name them YYYY-MM-something.ext for nice auto-captions,
       e.g. 2026-04-legoland-trip.webp → "Legoland trip · April 2026".
    3. Run: python3 update-gallery.py
    4. Existing captions in manifest.json are preserved — only new files get
       auto-captions. You can hand-edit the manifest to refine them.
    5. Commit and push. The Gallery tab on the site reads manifest.json on load.

Conventions:
    - Sort order is filename-descending (newest first if you use YYYY-MM- prefix).
    - Files starting with "." or "_" are ignored (treated as drafts).
"""
import json
import re
import sys
from pathlib import Path

SITE_DIR = Path(__file__).parent
PHOTOS_DIR = SITE_DIR / "photos"
MANIFEST = PHOTOS_DIR / "manifest.json"
INDEX_HTML = SITE_DIR / "index.html"
INLINE_START = "<!-- GALLERY-MANIFEST-START — auto-generated by update-gallery.py, do not hand-edit -->"
INLINE_END = "<!-- GALLERY-MANIFEST-END -->"
EXTENSIONS = {".webp", ".jpg", ".jpeg", ".png", ".gif"}

MONTHS = ["", "January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]


def _polish(text: str) -> str:
    """Tidy a string for use as a caption:
       - replace '-' and '_' with spaces
       - collapse multiple spaces
       - preserve original word capitalization (so 'TBI', 'BBQ', 'CNY' stay upper-case)
       - capitalize the first character if it's a lowercase letter
    """
    s = text.replace("-", " ").replace("_", " ").strip()
    s = re.sub(r"\s+", " ", s)
    if s and s[0].islower():
        s = s[0].upper() + s[1:]
    return s


def auto_caption(filename: str) -> tuple[str, str]:
    """Derive (caption, date) from a filename. Preserves original capitalization.

    Examples:
      20250919_with TBI friend in Toulouse.jpg -> ("with TBI friend in Toulouse", "September 2025")
                                                  → polished to ("With TBI friend in Toulouse", ...)
      20180620_Applikon visit.jpg              -> ("Applikon visit", "June 2018")
      2026-04-legoland.webp                    -> ("Legoland", "April 2026")
      2024-cny-celebration.webp                -> ("Cny celebration", "2024")
      lab-tea-2025.jpg                         -> ("Lab tea 2025", "")
    """
    stem = Path(filename).stem

    # Try YYYYMMDD prefix (8 digits, optionally with trailing digits like 20250101 14)
    m = re.match(r"^(\d{4})(\d{2})(\d{2})\d*[_\- ](.+)$", stem)
    if m:
        year, month, day, rest = m.groups()
        try:
            month_name = MONTHS[int(month)]
            date = f"{month_name} {year}"
        except (IndexError, ValueError):
            date = year
        return _polish(rest), date

    # Try YYYY-MM-rest pattern (dash or underscore)
    m = re.match(r"^(\d{4})[\-_](\d{2})[\-_](.+)$", stem)
    if m:
        year, month, rest = m.groups()
        try:
            month_name = MONTHS[int(month)]
            date = f"{month_name} {year}"
        except (IndexError, ValueError):
            date = year
        return _polish(rest), date

    # Try YYYY-rest pattern
    m = re.match(r"^(\d{4})[\-_](.+)$", stem)
    if m:
        year, rest = m.groups()
        return _polish(rest), year

    # Fallback
    caption = _polish(stem)
    return caption, ""


def scan() -> list[dict]:
    """Scan photos/ for image files. Returns list of {src, caption, date}."""
    if not PHOTOS_DIR.is_dir():
        print(f"ERROR: {PHOTOS_DIR} does not exist", file=sys.stderr)
        sys.exit(1)
    files = []
    for p in sorted(PHOTOS_DIR.iterdir(), reverse=True):
        if p.name.startswith(".") or p.name.startswith("_"):
            continue
        if p.suffix.lower() not in EXTENSIONS:
            continue
        files.append(p.name)
    return files


def load_existing() -> dict[str, dict]:
    """Return {src: entry} mapping from existing manifest, if any."""
    if not MANIFEST.exists():
        return {}
    try:
        data = json.loads(MANIFEST.read_text())
        return {entry["src"]: entry for entry in data.get("photos", [])}
    except (json.JSONDecodeError, KeyError, TypeError):
        return {}


def build_manifest(files: list[str], existing: dict[str, dict]) -> dict:
    """Build new manifest, preserving existing captions where filenames match."""
    photos = []
    for fname in files:
        src = f"photos/{fname}"
        if src in existing:
            # Keep existing caption + date — user may have edited manually
            photos.append(existing[src])
        else:
            caption, date = auto_caption(fname)
            entry = {"src": src, "caption": caption}
            if date:
                entry["date"] = date
            photos.append(entry)
    return {"photos": photos}


def main():
    dry = "--dry" in sys.argv
    rebuild = "--rebuild" in sys.argv
    files = scan()
    existing = {} if rebuild else load_existing()

    print(f"Found {len(files)} photo(s) in photos/")
    if rebuild:
        print("  --rebuild flag set: regenerating ALL captions from filenames (existing captions discarded)")
    new_count = sum(1 for f in files if f"photos/{f}" not in existing)
    removed = [src for src in existing if src.replace("photos/", "") not in files]

    if new_count and not rebuild:
        print(f"  + {new_count} new file(s) will be added")
    if removed:
        print(f"  - {len(removed)} entry/entries will be removed (file no longer in folder):")
        for src in removed:
            print(f"      {src}")

    manifest = build_manifest(files, existing)

    if dry:
        print("\n=== DRY RUN — manifest preview ===")
        print(json.dumps(manifest, indent=2, ensure_ascii=False))
        return

    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    print(f"\nWrote {MANIFEST}")
    print(f"  Total entries: {len(manifest['photos'])}")

    # Also embed the manifest inline in index.html so the gallery works on
    # file:// (where fetch() is blocked) as well as on the deployed server.
    inline_block = (
        f"{INLINE_START}\n"
        f"<script>\n"
        f"  window.__GALLERY_MANIFEST = {json.dumps(manifest, ensure_ascii=False)};\n"
        f"</script>\n"
        f"{INLINE_END}"
    )
    if INDEX_HTML.exists():
        html = INDEX_HTML.read_text()
        # Replace the existing inline block (matches start...end inclusive across lines)
        pattern = re.compile(re.escape(INLINE_START) + r".*?" + re.escape(INLINE_END), re.DOTALL)
        if pattern.search(html):
            new_html = pattern.sub(inline_block, html, count=1)
            INDEX_HTML.write_text(new_html)
            print(f"Updated inline manifest in {INDEX_HTML.name}")
        else:
            print(f"WARNING: inline manifest markers not found in {INDEX_HTML.name}")
            print(f"         (looking for {INLINE_START!r})")
            print(f"         The gallery will still work over http(s); only file:// is affected.")
    else:
        print(f"WARNING: {INDEX_HTML} not found — inline manifest not updated.")

    print("\nNext steps:")
    print("  1. (Optional) Open photos/manifest.json to refine any auto-captions,")
    print("     then re-run this script to sync the inline copy in index.html.")
    print("  2. git add photos/ index.html && git commit -m 'Update gallery' && git push")


if __name__ == "__main__":
    main()
